### ISSUE TITLE
大佬求带

### ISSUE THREAD

**Issue by jinfagang** [Jackiexiao/MTTS#1]
大佬很牛逼啊。我在跟你的项目，球带

**Comment by Jackiexiao** [comment]
比较喜欢写文档....实现中文前端+有个语料库，基本就可以用merlin做语音合成了，还在努力中

**Comment by jinfagang** [comment]
我有个聊天机器人，自己用注意力模型做的，也包括规则部分，目前对话可以容纳一个5万对的语料库，如果你能做合成，我们可以整个树梅派和麦克风阵列做个会说话的东西，并且可以拥有视觉观察的能力。
