### ISSUE TITLE
生成HTS label 出错

### ISSUE THREAD

**Issue by haiewu** [Jackiexiao/MTTS#11]
请问一下，为什么在txt里面，只要加了标点符号就会报错？？
Error at A11_0, please check your txt 绿是阳春烟景大块文章的底色#4四月的林峦更是绿得鲜活秀媚诗意盎然#4？
Prefix dict has been built succesfully.
 less than  绿 绿是阳春烟景大块文章的底色
 less than  是 绿是阳春烟景大块文章的底色
 less than  阳春 绿是阳春烟景大块文章的底色
 less than  烟景 绿是阳春烟景大块文章的底色
 less than  大块文章 绿是阳春烟景大块文章的底色
 less than  的 绿是阳春烟景大块文章的底色
equal : 底色
['#0', '#0', '#0', '#0', '#0', '#0', '#4', '#4']
less than  四月 四月的林峦更是绿得鲜活秀媚诗意盎然
 less than  的 四月的林峦更是绿得鲜活秀媚诗意盎然
 less than  林峦 四月的林峦更是绿得鲜活秀媚诗意盎然
 less than  更是 四月的林峦更是绿得鲜活秀媚诗意盎然
 less than  绿 四月的林峦更是绿得鲜活秀媚诗意盎然
 less than  得 四月的林峦更是绿得鲜活秀媚诗意盎然
 less than  鲜活 四月的林峦更是绿得鲜活秀媚诗意盎然
 less than  秀媚 四月的林峦更是绿得鲜活秀媚诗意盎然
 less than  诗意 四月的林峦更是绿得鲜活秀媚诗意盎然
equal : 盎然
['#0', '#0', '#0', '#0', '#0', '#0', '#4', '#0', '#0', '#0', '#0', '#0', '#0', '#0', '#0', '#0', '#4']
['#0', '#0', '#0', '#0', '#0', '#0', '#4', '#0', '#0', '#0', '#0', '#0', '#0', '#0', '#0', '#0', '#4', '#4']
ERROR   : Error at A11_0, please check your txt 绿是阳春烟景大块文章的底色#4四月的林峦更是绿得鲜活秀媚诗意盎然#4
INFO    : processing 2, file A11_1
 less than  他 他仅凭腰部的力量
 less than  仅凭 他仅凭腰部的力量
 less than  腰部 他仅凭腰部的力量
 less than  的 他仅凭腰部的力量
equal : 力量
['#0', '#0', '#0', '#0', '#4']
 less than  在 在泳道上下翻腾蛹动蛇行状如海豚一直以一头的优势领先
 less than  泳道 在泳道上下翻腾蛹动蛇行状如海豚一直以一头的优势领先
 less than  上下 在泳道上下翻腾蛹动蛇行状如海豚一直以一头的优势领先
 less than  翻腾 在泳道上下翻腾蛹动蛇行状如海豚一直以一头的优势领先
 less than  蛹 在泳道上下翻腾蛹动蛇行状如海豚一直以一头的优势领先
 less than  动 在泳道上下翻腾蛹动蛇行状如海豚一直以一头的优势领先
 less than  蛇行 在泳道上下翻腾蛹动蛇行状如海豚一直以一头的优势领先
 less than  状 在泳道上下翻腾蛹动蛇行状如海豚一直以一头的优势领先
 less than  如 在泳道上下翻腾蛹动蛇行状如海豚一直以一头的优势领先
 less than  海豚 在泳道上下翻腾蛹动蛇行状如海豚一直以一头的优势领先
 less than  一直 在泳道上下翻腾蛹动蛇行状如海豚一直以一头的优势领先
 less than  以 在泳道上下翻腾蛹动蛇行状如海豚一直以一头的优势领先
 less than  一头 在泳道上下翻腾蛹动蛇行状如海豚一直以一头的优势领先
 less than  的 在泳道上下翻腾蛹动蛇行状如海豚一直以一头的优势领先
 less than  优势 在泳道上下翻腾蛹动蛇行状如海豚一直以一头的优势领先
equal : 领先
['#0', '#0', '#0', '#0', '#4', '#0', '#0', '#0', '#0', '#0', '#0', '#0', '#0', '#0', '#0', '#0', '#0', '#0', '#0', '#0']
['#0', '#0', '#0', '#0', '#4', '#0', '#0', '#0', '#0', '#0', '#0', '#0', '#0', '#0', '#0', '#0', '#0', '#0', '#0', '#0', '#4']

**Comment by Jackiexiao** [comment]
sorry. a bug...在src/mandarin_frontend.py文件中第50行改成这个就好了，原先多加了一个#4
```
    if rhythms[-1] != '#4':
        rhythms.append('#4')
```

**Comment by haiewu** [comment]
非常感谢！不过我用我自己的数据进行生成label时，后面竟然报错了。。。
Setting up corpus information...
Number of speakers in corpus: 1, average number of utterances per speaker: 12005.0
Creating dictionary information...
Setting up training data...
Calculating MFCCs...
Calculating CMVN...
Number of speakers in corpus: 1, average number of utterances per speaker: 12005.0
Done with setup.
There were words not found in the dictionary. Would you like to abort to fix them? (Y/N)

**Comment by Jackiexiao** [comment]
提示的是有些拼音没有在字典里面出现过，所以无法做forced align，你可以查看输出目录下的文件，有一个提示了哪个句子的拼音出了问题，纠正即可，或者无视这个错误，选N
