### ISSUE TITLE
能将这个前端生成的label输入给HTS进行中文语音合成吗

### ISSUE THREAD

**Issue by zefric** [Jackiexiao/MTTS#12]
Hi,

非常感谢提供的这个前端！刚刚接触语音合成，可能会问一些基础的问题。

就是这个生成的label可以放到HTS里面进行语音合成吗？我试过了发现由单音素拼接成的声音起码还能听出点意思，但是在HTS中使用HHEd聚类后生成的有上下文连接关系的声音就不能听了。。。这个问题是不是和该前端生成的label格式与HTS的label的格式不一致有关？如果确实有关，那么有没办法解决呢？

合成的两种声音、label与原文都附在这上面了。

[单音素.zip](https://github.com/Jackiexiao/MTTS/files/2154121/default.zip)
[上下文.zip](https://github.com/Jackiexiao/MTTS/files/2154124/default.zip)
[label.zip](https://github.com/Jackiexiao/MTTS/files/2154130/label.zip)
[原文.txt](https://github.com/Jackiexiao/MTTS/files/2154131/default.txt)

**Comment by Jackiexiao** [comment]
我没有用过HTS，所以也无法回答这个问题。但是这个中文Label参照了HTS英文Label格式进行设计，只是细节上有些不同，例如每个位置代表的含义不同，请参阅[MTTS上下文标注设计规则](https://github.com/Jackiexiao/MTTS/blob/master/docs/mddocs/mandarin_label.md)，你可能需要自己去探索了。

此外，用HTS做语音合成可能已经过时了。

**Comment by zefric** [comment]
谢谢回复！我初步发现可能是问题集没有设置为中文问题集的原因。但是改了MTTS-master提供的中文问题集后也报错了：White space expected after command CQ。我观察到中文问题集文件中有CQS开头的内容，所以想请教一下为什么要使用CQS而不是QS呢？能否替换？

**Comment by Jackiexiao** [comment]
CQS是merlin加上的，你需要吧CQS的问题全部删掉，HTS只支持QS问题

**Comment by zefric** [comment]
[现在我把CQS的问题全部删掉了，也成功合成了语音。有个问题就是：删掉以后问题集就不完整了，[https://github.com/Jackiexiao/MTTS/blob/master/docs/mddocs/question.md](url) 并且这里提及了问题不是越多越好的，所以我需要补回哪些问题上去呢？

**Comment by Jackiexiao** [comment]
删去的这些问题可能对合成效果有影响，也可能影响不大，时间所限，我没有做过测试，只是让问题集尽可能多地覆盖了更多的特征，你可以设计实验改进这个问题集，保留最有用的部分，或者增加新的特征

**Comment by zefric** [comment]
作者你好！我又有新问题了。就是我观察了一下label文件，发现一个句子生成label中，除了静音的所有行的D E F层的标注都是相同的。我了解到这是和韵律有关的标注，看到问题集里也有相关的问题，但是label文件里面似乎没有体现出韵律的特征。想请教一下是我生成label的方法不太对还是这个前端是不包括韵律分析模块的呢？

**Comment by Jackiexiao** [comment]
这个前端是不包括韵律分析模块。

**Comment by zefric** [comment]
你好，我将带韵律的文本输入到src/mtts.py的时候又遇到了一些问题。

原韵律文本：`在#2中美#1双方的#1努力#1下#3两国#1关系#2近年来#2取得了#2一些#1进展#3特别是#2经贸#1合作#2发展#1较快#4`

然后我发现src/mandarin_frontend.py中的_adjust()函数会给我这段文字重新分词，分词结果大概是`在 中美 双方 的 努力 下 两国关系......`

注意到分词结果是将`两国`和`关系`合并在了一起，按照_adjust()函数的逻辑就是中间的#1会被删去。可是我得到的结果是这样的：

`equal : 在
['#2', '#1', '#1', '#1', '#3', '#1', '#2', '#2', '#2', '#1', '#3', '#2', '#1', '#2', '#1', '#4']
equal : 中美
['#2', '#1', '#1', '#1', '#3', '#1', '#2', '#2', '#2', '#1', '#3', '#2', '#1', '#2', '#1', '#4']
 less than  双方 双方的
equal : 的
['#2', '#1', '#0', '#1', '#1', '#3', '#1', '#2', '#2', '#2', '#1', '#3', '#2', '#1', '#2', '#1', '#4']
equal : 努力
['#2', '#1', '#0', '#1', '#1', '#3', '#1', '#2', '#2', '#2', '#1', '#3', '#2', '#1', '#2', '#1', '#4']
equal : 下
['#2', '#1', '#0', '#1', '#1', '#3', '#1', '#2', '#2', '#2', '#1', '#3', '#2', '#1', '#2', '#1', '#4']
两国关系 两国
equal : 两国关系
['#2', '#1', '#0', '#1', '#1', '', '#1', '#2', '#2', '#2', '#1', '#3', '#2', '#1', '#2', '#1', '#4']`

结果是#1前面的#3被删去了，#1没有变化。请问这是否正常呢？

**Comment by Jackiexiao** [comment]
感谢反馈，这是个bug，我有空会更正

**Comment by shartoo** [comment]
如果没有sfs文件提供时间信息的话，直接用文本生成的lab文件是没法应用于merlin的吧？但是TextToSpeech，理论上应该只需要提供文本信息吧？那个SFS文件是预估出来的？

**Comment by Jackiexiao** [comment]
duration model 用于估计每个音素的发音时间，无时间信息的lab输入到merlin duration model后会得到带时间信息的lab
