### ISSUE TITLE
关于merlin

### ISSUE THREAD

**Issue by shartoo** [Jackiexiao/MTTS#13]
您好！ 我从Merlin中转来的，看到您在Merlin mandarin中的问答。但是我一直无法正确运行 run_demo.sh脚本。 `conf/global_setting.conf`中的`Vocoder=WORLD`其实是错误的？因为实际只有小写的`world`,`world_v2`,可以用。所以这里好像需要修改，然后我修改了，也没法运行。在`run_demo.sh`的第6步，`06_traub_acoustic_model.sh` 中，出现错误
```
IndexError:index 0 is out of bounds for axis 0 with size 0
```
请问这个是因为在合成汉语的原因吗？还是我有什么其他地方做错了。
以及，我单独运行 `/merlin/misc/scripts/vocoder/world/extract_features_for_merlin.sh`会报错 `SPTK-2.9/x2x Permission denies`，但是其实我已经修改权限为777了，还是出现这个错误。运行完会有相应的输出。目前不知道哪里出错，如果有时间，能否帮我解决这个问题呢？

**Comment by Jackiexiao** [comment]
WORLD大写是正确的，你可以看一下merlin的相关脚本。此外确认一下 reaper  sptk world工具是否安装成功。权限问题可以自己网上查一下。记得修正这个[bug](https://github.com/CSTR-Edinburgh/merlin/pull/338)

**Comment by shartoo** [comment]
嗯，多谢！问题已经解决了，是因为Merlin的工具没有安装正确，我用了python3.6，要用python 2.7才行。
