### ISSUE TITLE
关于pau和sp的问题。

### ISSUE THREAD

**Issue by attitudechunfeng** [Jackiexiao/MTTS#14]
你好，我想问下你的音素表里包含了sil、pau和sp三个静音标志，在inference阶段，sil和pau还好理解，可以分别加在文本首尾和标点处，但是sp就没办法找到合适的位置加入了。这就意味着在测试阶段没法加入sp，所以在训练阶段对sp加以区分的意义还大吗？

**Comment by Jackiexiao** [comment]
其实意义不大，可以省去
