### ISSUE TITLE
字母和数字问题

### ISSUE THREAD

**Issue by shartoo** [Jackiexiao/MTTS#16]
我看代码里面是直接跳过了 阿拉伯数字和英文字母。是不是可以将数字转换为对应的中文文字呢，比如`3` --> `三`，英文字母不知道可不可以转换为近音字，`B`--> `俾`或者直接在音素词典中添加英文字母的音素呢

**Comment by Jackiexiao** [comment]
目前暂不支持数字&英文

**Comment by shartoo** [comment]
我的意思是在前端处理之前做这一步预处理，可以吗？

**Comment by Jackiexiao** [comment]
sure

**Comment by shartoo** [comment]
有个问题需要请教，像26个英文字母这种，有什么中文发音词典对应吗？像 `B`对应的`俾`，也是随意举例的，不太专业。

**Comment by Jackiexiao** [comment]
应该没有吧，我没有这么做过

**Comment by shartoo** [comment]
我从百度找到了一份。
![image](https://user-images.githubusercontent.com/5716282/44195373-6b62a680-a16b-11e8-8784-04b5473f9121.png)

不知道是否可用。
