### ISSUE TITLE
NO rhythm #2 ???

### ISSUE THREAD

**Issue by crystal0913** [Jackiexiao/MTTS#22]
Why there is no `#2` in the rhythm_map?
https://github.com/Jackiexiao/MTTS/blob/master/src/labformat.py#L9

在这个[function](https://github.com/Jackiexiao/MTTS/blob/master/src/labformat.py#L12)中也没有#2的处理，是有其他什么方式吗？
在King_tts_003语料库中，韵律分成四级，分别用`#4，#3，#2， #1`表示。

然后，这个地方就报错了[assert cur_rhythm in rhythm_map](https://github.com/Jackiexiao/MTTS/blob/master/src/labformat.py#L16)

**Comment by crystal0913** [comment]
OK, I got it. `#2`actually in this projec we regrad it as `#1`

**Comment by Jackiexiao** [comment]
yes, #2 is difficult to predict, but if you want to use, you could change the code
