### ISSUE TITLE
biaobei dataset error - not .wav format

### ISSUE THREAD

**Issue by crystal0913** [Jackiexiao/MTTS#25]
在用这个脚本`${merlin}/misc/scripts/vocoder/world/extract_features_for_merlin.sh`抽取声学特征时，
在biaobei数据集（采样率48000）上，大半wav文件（约004000以后，如010000.wav）都出现下面这个错误：
`fmt (2) error.`
`error: The file is not .wav format.`
其他的数据集如thchs30（采样率16000）、king-003（采样率44100）没这个问题。

**Comment by Jackiexiao** [comment]
如果是标贝部分音频有问题，部分没问题，那就是数据音频格式不一致了，你可以用sox什么的再处理一下。

**Comment by crystal0913** [comment]
@Jackiexiao 谢谢，解决了！参照merlin项目下的一个[issue](https://github.com/CSTR-Edinburgh/merlin/issues/314)，去掉wav文件的meta即可
`ffmpeg -y -i $filename -map_metadata -1 -codec copy $newfilename`
