### ISSUE TITLE
about “format pinyin to system's format”

### ISSUE THREAD

**Issue by yanyanxixi** [Jackiexiao/MTTS#4]
the function in txt2pinyin.py
def pinyinformat(syllabel):
translate_dict = {'ju':'jv', 'qu':'qv', 'xu':'xv', 'zi':'zic',
                      'ci':'cic', 'si':'sic', 'zhi':'zhih', 
                      'chi':'chih', 'shi':'shih', 'ri':'rih',
                      'yuan':'yvan', 'yue':'yve', 'yun':'yvn',
                      'iu':'iou', 'ui':'uei', 'un':'uen'}

why not translate ('quan':'qvan','xuan':'xvan','juan':'jvan','qun':'qvn','xun':'xvn') etc
the pypinyin result has "quan" and in mandarin_mtts.lexicon define the 
"quan1 q van1" etc

and if forcealignment use the mandarin_mtts.lexicon  and the system use another format
there are not one to one mapping.  will affect the result?

hope your replay
thanks a lot

**Comment by Jackiexiao** [comment]
@yanyanxixi Good issue, thx! This is my mistake, I should translate ('quan':'qvan','xuan':'xvan','juan':'jvan','qun':'qvn','xun':'xvn'). But actually those problem( including mandarin_mtts.lexicon not equal to system's format) will only slightly influence the result because DNN can learn the difference by context

**Comment by yanyanxixi** [comment]
and i have another question is 
when i change a sentence's internal order ,will have  a completely different result
for example
the sentence"你能命令风四面八方全刮一点吗?旷野的风要往这儿刮那儿刮“the result is ok
but sentence"旷野的风要往这儿刮那儿刮，你能命令风四面八方全刮一点吗?"is not good

can you give me some suggestions that how can i improve my reslut?
thank you!

**Comment by Jackiexiao** [comment]
I'm not sure about that, I will test it if I have time
