### ISSUE TITLE
WARNING:--Miss!

### ISSUE THREAD

**Issue by Ka6utack** [Jackiexiao/MTTS#5]
WARNING : --Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_249.TextGrid
流程走 用的还是那个<txt, wav>包，output一直warning：miss，我去翻源码，一边来Issues.

**Comment by Jackiexiao** [comment]
检查是否运行了`tools/install_mtts.sh`，如果运行了，里面的包是否下载完整？

**Comment by Ka6utack** [comment]
exactly! thanks for your works and your reply!

**Comment by Ka6utack** [comment]
依旧不行 重新bash run_demo.sh 依旧报miss 并没有缺省哪一个步骤 求解！

**Comment by Jackiexiao** [comment]
你把错误信息发上来，删掉重复的miss部分

**Comment by Ka6utack** [comment]
INFO    : Start montreal forced align
Error loading Python lib '/home/ka6utack/PycharmProjects/amazeWork/MTTS-master/tools/montreal-forced-aligner/bin/libpython3.5m.so.1.0': /home/ka6utack/PycharmProjects/amazeWork/MTTS-master/tools/montreal-forced-aligner/bin/libpython3.5m.so.1.0: cannot open shared object file: No such file or directory
酱紫！麻烦了！

**Comment by Jackiexiao** [comment]
montreal-forced-align没有安装成功。你是在linux上面跑吗，你单独下载[montreal-forced-align](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/releases/download/v1.0.0/montreal-forced-aligner_linux.tar.gz)解压在`mtts/tools`文件夹下，之后进入`montreal-forced-aligner/bin/`文件夹运行`./mfa_align`，如果运行正常没有报错那应该就没有问题了

**Comment by Ka6utack** [comment]
不行 我怀疑是这个montreal-forced-align文件包出错了 解压也会报错！

**Comment by Jackiexiao** [comment]
换个好一点的网络重新下载解压？

**Comment by Ka6utack** [comment]
./mfa_align
usage: mfa_align [-h] [-s SPEAKER_CHARACTERS] [-t TEMP_DIRECTORY]
                 [-j NUM_JOBS] [-v] [-n] [-c] [-d] [-e] [-i]
                 corpus_directory dictionary_path acoustic_model_path
                 output_directory
mfa_align: error: the following arguments are required: corpus_directory, dictionary_path, acoustic_model_path, output_directory

**Comment by Ka6utack** [comment]
权限777依旧这样！网速还是可以的.问题应该就是这一块！

**Comment by Jackiexiao** [comment]
montreal-forced-aligner usage:
`mfa_align corpus_directory, dictionary_path, acoustic_model_path, output_directory` 

see how this project use montreal-forced-aligner [source code here](https://github.com/Jackiexiao/MTTS/blob/master/src/mtts.py#L78)

If you install montreal-forced-align correctly, `bash run_demo.sh` should work well, if you still have problem on install montreal-forced-aligner, see [github-montreal-forced-aligner](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner) for help

**Comment by Ka6utack** [comment]
did you run it successfully? can i copy your steps in detail？i really want to find a feasible way of mandarin TTS！

**Comment by Jackiexiao** [comment]
After reinstall montreal-forced-aligner, have you run the `bash run_demo.sh` again? what's the output?

**Comment by Ka6utack** [comment]
the new output is the same with the before! your opinions is i did not follow the order?right?

**Comment by Ka6utack** [comment]
morning!

**Comment by Ka6utack** [comment]
okay!
