### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by v-yunbin** [Jackiexiao/MTTS#7]
my system is centos, must install libatlas-dev?
sudo yum install libatlas-dev

Trying other mirror.
Determining fastest mirrors
 * nux-dextop: li.nux.ro
No package libatlas-dev available.
Error: Nothing to do

**Comment by Jackiexiao** [comment]
libatlas-dev is used for [Montreal-forced-aligner](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner), see http://montreal-forced-aligner.readthedocs.io/en/latest/installation.html?highlight=libatlas3-base

I sometimes run montreal-forced-aligner successfully even without libatlas-dev. I'm not sure that if it works for centos system

**Comment by v-yunbin** [comment]
3ks,solved
