### ISSUE TITLE
.lab中文件格式是什么意思

### ISSUE THREAD

**Issue by yangxiaokang** [Jackiexiao/MTTS#9]
刚开始接触语音合成，问题可能比较基础
下边是A11_0.lab中的第一行，从第一个@之后我就看不懂了，麻烦解答一下
0 11000000 xx^xx-sil+l=v4@/A:xx-xx^xx@/B:xx+xx@xx^xx^xx+xx#xx-xx-/C:xx_xx^xx#xx+xx+xx&/D:xx=xx!xx@xx-xx&/E:xx|xx-xx@xx#xx&xx!xx-xx#/F:xx^xx=xx_xx-xx!

**Comment by yangxiaokang** [comment]
咱们没有做分词，是吗？

**Comment by Jackiexiao** [comment]
有的，用了结巴分词

**Comment by yangxiaokang** [comment]
你好，我想问下，.lab文件是怎么转成DNN模型的输入的？merlin有对应的脚本吗？

**Comment by Jackiexiao** [comment]
有的，通过问题集转换成相应唯度的向量，见：https://github.com/CSTR-Edinburgh/merlin/tree/master/egs/mandarin_voice/s1   代码位置为：https://github.com/CSTR-Edinburgh/merlin/blob/master/src/frontend/label_normalisation.py

**Comment by yangxiaokang** [comment]
在运行merlin中的run_demo.sh时，出现FileNotFoundError: [Errno 2] No such file or directory: '/merlin-master/egs/mandarin_voice/s1/experiments/mandarin_voice/duration_model/nnets_model/feed_forward_6_tanh.model'
应该是训练的模型没有保存下来，这个问题是需要修改一些配置吗？

**Comment by Jackiexiao** [comment]
你查看前面的输出，应该是前面的训练出了问题，你看下具体哪步出错了

**Comment by Jackiexiao** [comment]
顺利训练完的话，效果应该跟这个[网页](https://jackiexiao.github.io/MTTS/)上的是类似的，注意是训练集里面的，因为250句太少了
